### ISSUE TITLE
Part names

### ISSUE THREAD

**Issue by compvizard** [de-code/python-tf-bodypix#156]
When I specify the part names `['left_upper_arm_front', 'right_upper_arm_front']`, the mask highlights the **back** of the sitting lady's arms. When I switch to `['left_upper_arm_back', 'right_upper_arm_back']`, the mask highlights the **front** of the arms instead. Same issue for lower arms.

**Comment by de-code** [comment]
Thank you for raising the issue.

Just adding CLI commands to reproduce it potentially:


```bash
python -m tf_bodypix \
    draw-mask \
    --model-path=https://storage.googleapis.com/tfjs-models/savedmodel/bodypix/resnet50/float/model-stride16.json \
    --show-output \
    --threshold=0.75 \
    --mask-alpha=0.5 \
    --colored \
    --parts left_upper_arm_front right_upper_arm_front \
    --source \
    https://www.dropbox.com/s/7tsaqgdp149d8aj/serious-black-businesswoman-sitting-at-desk-in-office-5669603.jpg?dl=1
```

```bash
python -m tf_bodypix \
    draw-mask \
    --model-path=https://storage.googleapis.com/tfjs-models/savedmodel/bodypix/resnet50/float/model-stride16.json \
    --show-output \
    --threshold=0.75 \
    --mask-alpha=0.5 \
    --colored \
    --parts left_upper_arm_back right_upper_arm_back \
    --source \
    https://www.dropbox.com/s/7tsaqgdp149d8aj/serious-black-businesswoman-sitting-at-desk-in-office-5669603.jpg?dl=1
```

To be honest I am having difficulty telling front and back apart.
What image are you using?

The part names seem to match [tfjs-models](https://github.com/tensorflow/tfjs-models).
Would you say it is any better with [tfjs-models](https://github.com/tensorflow/tfjs-models)?

**Comment by compvizard** [comment]
I’m using the same image: serious-black-businesswoman-sitting-at-desk-in-office. I get the feeling that “front” means where the arms face outwards away from the shoulders and “back” means where the arms face inwards towards the armpit and chest. I had expected “front” to be part of the arms facing forward and “back” to be the parts facing backwards. So perhaps this is not a bug, just differences in interpretation. Thanks for the response, anyway.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by de-code** [comment]
Do you think the issue can be closed?
(If there are inconsistencies with the bodypix model in [tfjs-models](https://github.com/tensorflow/tfjs-models) then I could look into it.)
