### ISSUE TITLE
Could not download josn file

### ISSUE THREAD

**Issue by dickkky** [de-code/python-tf-bodypix#26]
There is an error occured when I run "bodypix_model = load_model(download_model(
    BodyPixModelPaths.MOBILENET_RESNET50_FLOAT_STRIDE_32".
"Expectation: URL fetch failure on https://storage.googleapis.com/tfjs-models/savedmodel/bodypix/resnet50/float/model-stride32.json:404 Not Found

**Comment by de-code** [comment]
Thank for raising the issue. The constants for the resnet URLs contained `savedmodel/bodypix` twice, although it doesn't show up in your message.

This should work now:

```python
import tensorflow as tf
from tf_bodypix.api import download_model, load_model, BodyPixModelPaths

bodypix_model = load_model(download_model(
    BodyPixModelPaths.MOBILENET_RESNET50_FLOAT_STRIDE_32
))
```

Alternatively you can also see the list of available URLs via:

```bash
python -m tf_bodypix list-models
```
