### ISSUE TITLE
Incorrect path concatenation

### ISSUE THREAD

**Issue by EltonCN** [de-code/python-tf-bodypix#46]
Using with Windows, the "os.path.join(model_base_path, weights_manifest_path)" in line 81 of download.py generates a wrong URL with "\" separator.

Changing to "model_base_path+"/"+weights_manifest_path" corrected the problem

**Comment by de-code** [comment]
Thank you for reporting the issue. I guess that is only an issue when `model_base_path` is not a local path?

**Comment by de-code** [comment]
It's fixed in source and will be included in the next release

**Comment by de-code** [comment]
The fix is now released (v0.3.3)
