### ISSUE TITLE
Part Segmentation Object - pose detection

### ISSUE THREAD

**Issue by zebediz** [de-code/python-tf-bodypix#50]
Hi, 

On the bodypix github page, the javascript bodypix version shows a keypoint skeleton which seems to be an allPoses field returned from the segmentPerson() call. Is it possible to get these pose locations from the python api? (ie a list of keypoints with their (x,y) locations)

**Comment by de-code** [comment]
Hi @zebediz 

That hasn't been ported yet. But would be a good addition. Would you be interested in working on a PR?
