### ISSUE TITLE
AutoFrame feature for software

### ISSUE THREAD

**Issue by benbatya** [de-code/python-tf-bodypix#67]
This app is really cool. It's got 100% of the functionality I need on Linux to replicate Zoom's BG subtraction on Mac/Win. 
Now, I want a feature where the face mask is used to crop the output image from ReplaceBackgroundApp.get_output_image() and then rescale that to the output image size.

So the face would be "tracked" regardless of where it goes in the frame ala AutoFrame from Nvidia (https://youtu.be/GRFjfGH87Dk?t=55)

Assign this to me

**Comment by de-code** [comment]
Hi @benbatya thank you for your suggestion.
This seems to have an interesting feature to have.

For now I would suggest for a feature like this to live outside this repository.
I would like to keep this project relatively light to encourage others to include it, if they only want to use the bodypix model.

I had started [layered-vision](https://github.com/de-code/layered-vision), which has a broader scope. So perhaps that could be a good home?

I should also mention [virtual_webcam_background](https://github.com/allo-/virtual_webcam_background) (GPL licensed), which is a project I used, before trying out my own implementation. It doesn't currently use `tf-bodypix`, but there is an [issue #47](https://github.com/allo-/virtual_webcam_background/issues/47) for that.

What do you think about starting with a separate script (gist?) to experiment with your suggested feature and then we could see how to best integrate it? I guess it might also need a bit of #50 (although just looking for the face should be easier)

**Comment by benbatya** [comment]
Hi @de-code sure, here's a gist. I hope that the patch format works. 
https://gist.github.com/benbatya/59e717c50a22e1e8278918d04bb06cd6

Yeah, I'll check out layered-vision vs virtual_webcam_background. 
I am curious if you started layered-vision because of issues with VWB or more to scratch a coding itch.
I'm happy to implement the feature in either project, it's a fairly simple additional filter...

**Comment by benbatya** [comment]
After looking at layered-vision, it's a good framework. I'll implement the filter there.
Tracking issue is https://github.com/de-code/layered-vision/issues/56

**Comment by de-code** [comment]
> I am curious if you started layered-vision because of issues with VWB or more to scratch a coding itch.

Yes, it was a combination of things probably. In part I wanted to try a quite different architecture. I thought a kind of graph like architecture may allow for more optimisation later on (e.g. only calculate layers or parts needed).
