### ISSUE TITLE
Add ability to play looping videos in replace-background mode

### ISSUE THREAD

**Issue by benbatya** [de-code/python-tf-bodypix#68]
Right now, only PIL is supported for the --background argument. 
Change ReplaceBackgroundApp.get_image_source() check if the video extension is a video and use a video loading API (maybe scikit-video or ffmpeg-python?) to lazy load frames and return them as the background image

**Comment by de-code** [comment]
Hi @benbatya thank you for this suggestion as well.
As mentioned in #67, the scope of this project is a bit limited. Although videos could be added for demonstration purpose with relatively little overhead.

You might be interested to know, that [layered-vision](https://github.com/de-code/layered-vision) does actually support videos using OpenCV (both preloaded and on-demand). And I was thinking of adding other sources there as well (e.g. screen sharing).
([virtual_webcam_background](https://github.com/allo-/virtual_webcam_background) also supports preloaded videos)

Perhaps I could move the CLI to a separate project and add more features there (which is somewhat the purpose of `layered-vision`).

**Comment by benbatya** [comment]
Closing this in deference to other projects.
